### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#19]
- [x] Revisit the world and physics modules code, some world module code currently contains physics code (of server) and such
- [ ] Revisit the client, server and network modules, move some other module-specific code in proper module (network-specific code -> network module)
- [ ] Make dedicated launcher buildable
- [x] Rewrite dedicated launcher code to use new API or impl an old in engine module
- [ ] Check that vgui module is buildable
- [ ] Finish vgui2
- [ ] Impl export funcs of vstdlib and dbg modules
- [ ] Deal with engine-merge code
- [ ] Remove duplications between hlsdk and our codebase code
- [ ] Merge NetQuake, QW and Q2 codebases
