### ISSUE TITLE
Client-side TODO

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#40]
Client-side is still pretty raw
GS has more changes that Quake and Xash summarized...

**TODO:**
- [ ] Protocol messages parsing;
- [ ] Prediction;
- [ ] ???
- [ ] Lotta other things I even dunno;
- [ ] Render module support is definitely broken (Q2 render was applied above QW sources);
- [ ] Rip out the sound module?;

**Comment by Sh1ft0x0EF** [comment]
### Client Protocol
* Partially the same as in Quake
* Some of the entries are unused
* Some of the entries are easy to reimplement
* Some of the entries are implemented in Xash but I'm not sure about using it atm...

**Comment by Sh1ft0x0EF** [comment]
### cl_input and client input cvars
As I mentioned earlier, lotta these things were moved to clientdll so I should just clearly remove 'em from the engine codebase
But
I'm still not sure about % of compatibility with the gs' clientdll but wanna test it when it finally would be compilable even if wouldn't be able to support it

**Comment by Sh1ft0x0EF** [comment]
Looks like there is no calls to IN_Init/IN_Shutdown inside the engine
So there are only callbacks calling functions (for mouse control and cmd generation)
I'm not sure that all the old remnant IN_* funcs doing is calling back a client dll versions but that's it according to GSR
